#!/bin/bash
# ---------------------------------------------------------------
# harness/import.sh -- Import a user's own QEMU VM image
#
# Usage:
#   bash harness/import.sh /path/to/your-vm-image.qcow2 [ssh-port] [ssh-user]
#
# This script:
#   1. Generates angband SSH keys (if not already present)
#   2. Prints the public key for the user to add to their VM
#   3. Creates a qcow2 overlay snapshot backed by the user's image
#   4. Generates a launch script tailored to the imported image
#
# The user's original image is NEVER modified.
# ---------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
RUNTIME_ROOT="$REPO_ROOT/mordor_run"
HARNESS_DIR="$RUNTIME_ROOT/harness"
SSH_DIR="$RUNTIME_ROOT/ssh"
SSH_KEY="$SSH_DIR/id_ed25519"
OVERLAY_IMAGE="$HARNESS_DIR/disk.qcow2"

# ------ Parse arguments ------

if [ $# -lt 1 ]; then
    echo "Usage: bash harness/import.sh <path-to-vm-image> [ssh-port] [ssh-user]"
    echo ""
    echo "  <path-to-vm-image>  Path to your qcow2/raw VM disk image"
    echo "  [ssh-port]          SSH port forwarded to the guest (default: 2222)"
    echo "  [ssh-user]          Username in the guest (default: ubuntu)"
    echo ""
    echo "Example:"
    echo "  bash harness/import.sh ~/my-kernel-test-vm.qcow2 2222 testuser"
    exit 1
fi

USER_IMAGE="$1"
SSH_PORT="${2:-2222}"
SSH_USER="${3:-ubuntu}"

# ------ Validate image ------

if [ ! -f "$USER_IMAGE" ]; then
    echo "[!] Image not found: $USER_IMAGE"
    exit 1
fi

# Get absolute path
USER_IMAGE=$(cd "$(dirname "$USER_IMAGE")" && pwd)/$(basename "$USER_IMAGE")

IMAGE_FORMAT=$(qemu-img info --output=json "$USER_IMAGE" 2>/dev/null | grep '"format"' | awk -F'"' '{print $4}')
if [ -z "$IMAGE_FORMAT" ]; then
    echo "[!] Cannot read image: $USER_IMAGE"
    echo "    Make sure qemu-img is installed and the file is a valid disk image."
    exit 1
fi

echo "============================================"
echo "  Angband -- Import Custom VM Image"
echo "============================================"
echo ""
echo "  Image:   $USER_IMAGE"
echo "  Format:  $IMAGE_FORMAT"
echo "  SSH:     port=$SSH_PORT  user=$SSH_USER"
echo ""

# ------ Step 1: Generate SSH keys ------

mkdir -p "$HARNESS_DIR" "$SSH_DIR"

echo "[Step 1] SSH key pair"
if [ -f "$SSH_KEY" ]; then
    echo "[+] SSH key already exists: $SSH_KEY"
else
    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -q
    echo "[+] Generated: $SSH_KEY"
fi

PUB_KEY=$(cat "$SSH_KEY.pub")
echo ""
echo "============================================"
echo "  ACTION REQUIRED"
echo "============================================"
echo ""
echo "  You must add this public key to your VM's"
echo "  ~/.ssh/authorized_keys file."
echo ""
echo "  Public key:"
echo "  $PUB_KEY"
echo ""
echo "  Quick method (if your VM is currently running):"
echo ""
echo "    ssh -p $SSH_PORT $SSH_USER@localhost \\"
echo "      'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys' \\"
echo "      <<< '$PUB_KEY'"
echo ""
echo "  Or copy-paste manually into the VM."
echo ""

# ------ Step 2: Wait for confirmation ------

read -p "  Press ENTER after adding the key to your VM (or Ctrl-C to abort)... " _

# ------ Step 3: Create overlay snapshot ------

echo ""
echo "[Step 2] Creating overlay snapshot..."

if [ -f "$OVERLAY_IMAGE" ]; then
    echo "[*] Removing old overlay..."
    rm -f "$OVERLAY_IMAGE"
fi

qemu-img create -f qcow2 -b "$USER_IMAGE" -F "$IMAGE_FORMAT" "$OVERLAY_IMAGE" 2>/dev/null
echo "[+] Overlay: $OVERLAY_IMAGE"
echo "    Backed by: $USER_IMAGE (read-only, never modified)"

# ------ Step 4: Save import config ------

cat > "$HARNESS_DIR/import.conf" <<EOF
# Angband import configuration
# Generated by harness/import.sh
USER_IMAGE=$USER_IMAGE
IMAGE_FORMAT=$IMAGE_FORMAT
SSH_PORT=$SSH_PORT
SSH_USER=$SSH_USER
IMPORTED_AT=$(date -Iseconds)
EOF

echo "[+] Config saved: $HARNESS_DIR/import.conf"

# ------ Step 5: Test SSH ------

echo ""
echo "[Step 3] Testing SSH connection..."
echo "  Make sure your VM is running with SSH forwarded to port $SSH_PORT."
echo ""

if ssh -o StrictHostKeyChecking=no \
       -o UserKnownHostsFile=/dev/null \
       -o ConnectTimeout=5 \
       -o LogLevel=ERROR \
       -i "$SSH_KEY" \
       -p "$SSH_PORT" \
       "$SSH_USER@localhost" \
       "echo SSH_OK && uname -r" 2>/dev/null; then
    echo "[+] SSH connection successful!"
else
    echo "[!] SSH connection failed."
    echo "    Make sure:"
    echo "    1. Your VM is running"
    echo "    2. SSH is forwarded: -net user,hostfwd=tcp::${SSH_PORT}-:22"
    echo "    3. The public key is in ~/.ssh/authorized_keys"
    echo ""
    echo "    You can still use angband -- just start your VM with:"
    echo "      bash harness/launch.sh"
    echo "    which will use the overlay snapshot."
fi

# ------ Done ------

echo ""
echo "============================================"
echo "  Import complete!"
echo "============================================"
echo ""
echo "  Your VM is ready for angband. Workflow:"
echo ""
echo "    # Generate exploit"
echo "    angband init demo"
echo "    angband generate"
echo ""
echo "    # Start your VM (if not already running)"
echo "    bash harness/launch.sh"
echo ""
echo "    # Run the exploit"
echo "    bash run_and_verify.sh"
echo ""
echo "  To reset the overlay (discards all VM changes):"
echo "    bash harness/reset.sh"
echo ""
echo "  SSH access:"
echo "    ssh -i mordor_run/ssh/id_ed25519 -p $SSH_PORT $SSH_USER@localhost"
echo ""
